services:
  redis:
    image: redis:latest
    container_name: shemtong-radis
    hostname: ${REDIS_HOST}
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: ${REDIS_HOST}
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - /home/ubuntu/redis-data:/data
    restart: on-failure

  springboot:
    image: semtongserver
    env_file:
      - .env
    container_name: semtongserver
    build: .
    ports:
      - "8080:8080"
    environment:
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      DB_USER: ${DB_USER}
      DB_URL: ${DB_URL}
      DB_PASSWORD: ${DB_PASSWORD}

    restart: always
volumes:
  redis_data: