spring:
  application:
    name: shemtong

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.79.34.144:3306/shemtong
    username: root
    password: ahdzlehdud

  jpa:
    hibernate:
      ddl-auto: create

jwt:
  secret: aosidfhioahsdokjtlqopsdotqljdlkfhqothoasodhotqnokewmsdohtqoinasdhoifhotlqsdhaoithqokjdsklfj