name: deploy

on:
  push:
    branches:
      - main


jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: ssh to ec2
        uses: appleboy/ssh-action@v0.1.6
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USER }} 
          script: |
            set -e
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
            chmod 600 private_key.pem
            ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} "echo 'Connected successfully'" -v

            PID=$(lsof -t -i:8080)
            if [ -z "$PID" ]; then
              echo "No process is running on port 8080"
            else
              echo "Killing process $PID"
              kill -9 $PID
            fi
            cd shemtongserver
            git pull
            sh gradlew build
            cd build/libs
            nohup java -jar shemtongserver-0.0.1-SNAPSHOT.jar > ~/5c0_server/nohup.out 2>&1 &
